version: "3"

services:
    web:
        image: easter/web
        container_name: easter-web
        tty: true
        build:
          context: ./web
          dockerfile: dockerfile
        ports:
          - "3000:3000"
        networks:
          - easter-net
        volumes:
          - ./ops:/easter/ops
          - ./web:/easter/web
        env_file:
          - ./ops/local.env
    api:
        image: easter/api
        container_name: easter-api
        tty: true
        build:
            context: ./api
            dockerfile: dockerfile
            args:
            - API_PORT=3001
            - OPS_PORT=3002
        ports:
            - "3001:3001"
        networks:
            - easter-net
        volumes:
            - ./ops:/easter/ops
            - ./api:/easter/api
        env_file:
            - ./ops/local.env
    localstack:
        image: localstack/localstack
        container_name: easter-localstack
        networks:
            - easter-net
        ports:
            - "8080:8080"
        volumes:
            - localstack_data:/tmp/localstack
    
    dynamodb-admin:
        image: aaronshaf/dynamodb-admin
        container_name: easter-dynamodb-admin
        ports:
            - "8001:8001"
        environment:
            - DYNAMO_ENDPOINT=http://localstack:4569
        networks:
            - easter-net

networks:
    easter-net:
        driver: bridge

volumes:
    www_modules:
    localstack_data: